### ISSUE TITLE
_で始まるローカル変数

### ISSUE THREAD

**Issue by ryutorion** [AngularSpectrumMTD/Optical_simulator#1]
__ (アンダースコア2つ)または _X (アンダースコアの後に大文字)の識別子，または _ (アンダースコア)で始まるグローバル名前空間の名前は予約されています．

そういったルールを覚えるのも面倒ですし，グローバル名前空間の名前とぶつかっても面倒なので，基本的にはアンダースコアで始まる名前は避けた方が良いでしょう．

**Comment by AngularSpectrumMTD** [comment]
修正完了です．
