### ISSUE TITLE
マクロ以外での大文字の識別子は避ける

### ISSUE THREAD

**Issue by ryutorion** [AngularSpectrumMTD/Optical_simulator#10]
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Renum-caps

全体的にenumを大文字で定義しているようですが，止めた方が良いです．
マクロとぶつかって置換される可能性もあります．

ついでに，typedef struct XXX { } XXX; などの書き方はCまでの書き方で，C++ではtypedefは不要です．

**Comment by AngularSpectrumMTD** [comment]
修正完了です．
