### ISSUE TITLE
不要なメモリの確保を行っている

### ISSUE THREAD

**Issue by ryutorion** [AngularSpectrumMTD/Optical_simulator#11]
https://github.com/AngularSpectrumMTD/Optical_simulator/blob/c61eea0f199be0bf706cd68f90705d60ae69145e/cpp/CalcObjectField.cpp#L833

処理を見るに，x，y，zの最大値と最小値が欲しいだけのようなので，次のようなコードで十分だと思います．

```
vec3 min_value(vec[0]);
vec3 max_value(vec[0]);

for(auto & v : vec)
{
  min_value = minPerElem(min_value, v);
  max_value = maxPerElem(max_value, v);
}

bbox._min = min_value;
bbox._max = max_value;
```

メモリの確保は若干重い処理なので，回数や量を減らせるなら減らした方が良いです．

**Comment by AngularSpectrumMTD** [comment]
修正完了です．
