### ISSUE TITLE
インデントするならブロックも付けた方が良い

### ISSUE THREAD

**Issue by ryutorion** [AngularSpectrumMTD/Optical_simulator#12]
https://appllio.com/20140223-4899-apple-ios-bug-ssl-goto-fail

このように，インデントでforやifに対応した処理だと表していると，間違えたときに気付きにくくなるので，可能な限り { と } を付ける方が良いです．

最初からブロックにしていれば，後から書き換えたときなどにも間違えにくくなります．

**Comment by AngularSpectrumMTD** [comment]
修正完了です．
