### ISSUE TITLE
仮引数にもconstを付けた方が良いです

### ISSUE THREAD

**Issue by ryutorion** [AngularSpectrumMTD/Optical_simulator#13]
関数内で変更するつもりが無い仮引数にはconstを付けるようにした方が良いです．
特に参照で渡している場合，誤って変更してしまうことを防げますし，変化しないということで最適化がかかりやすくなることもあります．

また，インターフェースだけを見た場合に，内部で値が変更されない，と読む側に伝わることで，安心して値を渡すことができるようになります．

**Comment by AngularSpectrumMTD** [comment]
修正完了です．
