### ISSUE TITLE
ヘッダファイルとソースファイルの対応付けが分からない

### ISSUE THREAD

**Issue by ryutorion** [AngularSpectrumMTD/Optical_simulator#14]
ヘッダファイルの実装が複数のファイルに分割され，その名前にも直接の関連付けが無いので，この実装はどのファイルにあるのか，ということが非常に分かりにくくなっています．

Visual Studioなどにはヘッダファイルとソースファイルを行き来する機能がありますが，このコードの作りだと機能しないのではないでしょうか?

例えば，WaveFront.hの実装を複数のファイルに分けるとしても，WaveFront_BasicFuncion.cppなどWaveFrontの実装と分かるようにするなどしないと，読む相手を混乱させます．

**Comment by AngularSpectrumMTD** [comment]
修正完了です．
