### ISSUE TITLE
setter/getterと思わせておいて複雑な処理をしない方が良い

### ISSUE THREAD

**Issue by ryutorion** [AngularSpectrumMTD/Optical_simulator#17]
setter/getterは単純な処理と思って呼び出すので，あまりに複雑で時間がかかりそうな処理にもget/setと付けていると，変な使い方をして速度低下を招くことがあります．

The Art of Readable Codeの2章などを参考に，関数内で画像全体にループしているようなgetやsetは名前を変えた方が良いでしょう．

**Comment by AngularSpectrumMTD** [comment]
一旦ComputeやGenerateという単語で関数名を書き換えておきました
