### ISSUE TITLE
余分なconstがあります

### ISSUE THREAD

**Issue by ryutorion** [AngularSpectrumMTD/Optical_simulator#18]
https://github.com/AngularSpectrumMTD/Optical_simulator/blob/b383a2a2a0ded73f37be4db387e82ea4daa94ec3/include/WaveFront.h#L126

constが2つ書いているため，警告が出ます．
機械的に置換したのではないでしょうか?

**Comment by AngularSpectrumMTD** [comment]
ご指摘の通り機械的に置換したため余分なconstがありますね．
修正しておきます．

**Comment by AngularSpectrumMTD** [comment]
消しておきました．
