### ISSUE TITLE
キャストはC++形式を

### ISSUE THREAD

**Issue by ryutorion** [AngularSpectrumMTD/Optical_simulator#4]
[Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html#Casting)などにもあるように，C++では可能な限りC++で追加されたstatic_castやreinterpret_castといったキャストを使った方が良いです．

キャストの検索しやすさも上がります．ただ，横に長くなるのが問題ですが．

C形式のキャストを使っていると，強制的にキャストする関係でC++形式のキャストであれば気付けていた問題に気付けない場合があります．
例えば，C形式のキャストだと型が合わない関数の関数ポインタを無理やりキャストしてしまうことも可能です．

**Comment by AngularSpectrumMTD** [comment]
修正完了です．
