### ISSUE TITLE
WaveFront::GetInterpolatedValueのswtichにdefaultが無い

### ISSUE THREAD

**Issue by ryutorion** [AngularSpectrumMTD/Optical_simulator#5]
https://github.com/AngularSpectrumMTD/Optical_simulator/blob/c61eea0f199be0bf706cd68f90705d60ae69145e/cpp/Interpolation.cpp#L150

defaultが無いため，補間方法が増えた場合にreturnを通らずに関数が終わる可能性があります．デフォルト値を決めるか，switch文を素通りした場合のreturnを最後に入れておいた方が良いでしょう．

**Comment by AngularSpectrumMTD** [comment]
修正完了です．
