### ISSUE TITLE
ヘッダでのusing namespaceは避ける

### ISSUE THREAD

**Issue by ryutorion** [AngularSpectrumMTD/Optical_simulator#6]
https://github.com/AngularSpectrumMTD/Optical_simulator/blob/c61eea0f199be0bf706cd68f90705d60ae69145e/header/Image.h#L18

ヘッダにusing namespaceを書いてしまうと，インクルード先で思わぬ名前の衝突が起こる可能性があります．

基本的に，ヘッダにはusing namespaceは書かないようにしましょう．

その下の方に，using namespace stdもあって，こっちはさらに凶悪です．
絶対にやってはいけません．

**Comment by AngularSpectrumMTD** [comment]
修正完了です．
