### ISSUE TITLE
mallocで確保したメモリをキャストしてクラスへのポインタとしている

### ISSUE THREAD

**Issue by ryutorion** [AngularSpectrumMTD/Optical_simulator#7]
https://github.com/AngularSpectrumMTD/Optical_simulator/blob/c61eea0f199be0bf706cd68f90705d60ae69145e/header/Image.h#L130

この書き方では，コンストラクタは実行されません．mallocを使うのであれば，mallocで確保したメモリ領域に対してplacement newを使う必要があります．

実際のところ，ここは以下の書き方で十分です．

```
Image * Create_Image(int width, int height)
{
    return new Image(width, height);
}
```

ちなみに，この関数って既にImageオブジェクトが無いと使えないものですが，何のためにあるのでしょう?
staticな関数にしても良い気がしますが．

**Comment by AngularSpectrumMTD** [comment]
修正完了です．

**Comment by ryutorion** [comment]
何をどう直したのか不明すぎます……
