### ISSUE TITLE
Image::Read_Bmpでメモリリークしています

### ISSUE THREAD

**Issue by ryutorion** [AngularSpectrumMTD/Optical_simulator#8]
https://github.com/AngularSpectrumMTD/Optical_simulator/blob/c61eea0f199be0bf706cd68f90705d60ae69145e/header/Image.h#L182

直前の部分でmallocで確保したメモリを解放せずにnewで確保したメモリをポインタに格納しているので，Create_Imageで確保したメモリは解放されずにリークしています．

[Visual Studioのドキュメント](https://docs.microsoft.com/ja-jp/visualstudio/debugger/finding-memory-leaks-using-the-crt-library?view=vs-2019)を参考に，メモリリークのチェックをした方が良いでしょう．

**Comment by AngularSpectrumMTD** [comment]
修正完了です．
