### ISSUE TITLE
複雑すぎる実装をヘッダに書かない

### ISSUE THREAD

**Issue by ryutorion** [AngularSpectrumMTD/Optical_simulator#9]
Image.hなどでヘッダに何行にもわたる実装を書いています．

実装の修正をするたびに，ヘッダファイルをインクルードしているファイルもコンパイルが必要になります．

簡単なreturn文や，実装が固定されていて滅多に変わらないことが明らかでなければ，ヘッダファイルには実装を書かない方が良いでしょう．

規模が大きくなればなるほど，再ビルドの時間の長さが問題になります．

**Comment by AngularSpectrumMTD** [comment]
修正完了です．
